### ISSUE TITLE
Cortex-m-rtfm quickstart template?

### ISSUE THREAD

**Issue by perlindgren** [rtic-rs/rfcs#26]
There is a quickstart for `cortex-m-rt`.
Its an excellent starting point for a bare metal project, and from there one can start adding `rtfm` specifics.

Goal is to make it as easy as possible to get started with RTFM.

Would we want a separate quickstart for `cortex-m-rtfm`, or alternatively would it be possible to make `cortex-m-rt` quickstart support RTFM (through some cli option).

**Comment by korken89** [comment]
I think we should do this, low effort and a good reference

**Comment by perlindgren** [comment]
This now available (thanks @korken89 ). So I close this issue, please re-open if needed.
